### ISSUE TITLE
Realizando o registo após o cancelamento

### ISSUE THREAD

**Issue by luanyata** [Andrevmatias/Glic#38]
Ao clica no (+) para realizar o registro digitar algum valor em qualquer campo, clicar em voltar para desistir de registrar o mesmo acaba efetuando o registro

**Comment by Andrevmatias** [comment]
Este é um comportamento comum de aplicativos do tipo, pois muitas vezes o usuário não clica em "salvar" para salvar o resultado por estar distraído/com pressa

**Comment by Andrevmatias** [comment]
Foi criado o issue #41
